/*
 * Copyright (C) 2014 alex
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package classdiagrameditor;

import java.util.Set;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author alex
 */
public class ClassPropertiesForm extends javax.swing.JPanel
    implements SelectionObserver, DocumentListener
{
    private ClassElement element_;

    /**
     * Creates new form ClassPropertiesForm
     */
    public ClassPropertiesForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        attributesTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        operationsTable = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 5, 10, 5));
        setPreferredSize(new java.awt.Dimension(200, 768));

        nameText.setEnabled(false);
        nameText.getDocument().addDocumentListener(this);

        attributesTable.setModel(new ClassPropertiesTableModel(ClassElement.PropertiesType.ATTRIBUTES)
        );
        attributesTable.setDragEnabled(true);
        attributesTable.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        jScrollPane1.setViewportView(attributesTable);

        operationsTable.setModel(new ClassPropertiesTableModel(ClassElement.PropertiesType.OPERATIONS));
        operationsTable.setDragEnabled(true);
        operationsTable.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        jScrollPane2.setViewportView(operationsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
            .addComponent(nameText)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(424, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable attributesTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameText;
    private javax.swing.JTable operationsTable;
    // End of variables declaration//GEN-END:variables

    public void notifySelectionChanged(Set<Element> selection) {
        element_ = null;
        if (selection.size() == 1) {
            for (Element e : selection) {
                if (e instanceof ClassElement) {
                    element_ = (ClassElement)e;
                }
            }
        }
        ((ClassPropertiesTableModel)attributesTable.getModel()).setElement(element_);
        ((ClassPropertiesTableModel)operationsTable.getModel()).setElement(element_);

        nameText.setEnabled(element_ != null);
        nameText.setText(element_ == null ? "" : element_.getName());
    }

    private void nameTextChanged() {
        if (element_ == null) return;

        element_.setName(nameText.getText());
    }

    public void insertUpdate(DocumentEvent e) {
        nameTextChanged();
    }

    public void removeUpdate(DocumentEvent e) {
        nameTextChanged();
    }

    public void changedUpdate(DocumentEvent e) {
        nameTextChanged();
    }
}
