/*
 * Copyright (C) 2014 Patrick
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package classdiagrameditor;

import java.util.Set;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Patrick
 */
public class RelationshipPropertiesForm extends javax.swing.JPanel 
       implements SelectionObserver {
        
    /**
     * Creates new form RelationshipPropertiesForm
     */
    private RelationshipElement element_;
    private DiagramManager diagram_;
    
    public RelationshipPropertiesForm() {
        initComponents();
        setVisible(false);
        
        NameTextField.getDocument().addDocumentListener(new RelationDocumentListener());
    }
    
    @Override
    public void notifySelectionChanged(DiagramManager diagram, Set<Element> selection) {

        element_ = null;
        diagram_ = diagram;
        if (selection.size() == 1) {
            for (Element e : selection) {
                if (e instanceof RelationshipElement) {
                    element_ = (RelationshipElement)e;                   
                    
                    NameTextField.setText(element_.getLabel());
                    SourceMultTextField.setText(element_.getSrcMultiplicity());
                    DestMultTextField.setText(element_.getDestMultiplicity());
                }
            }
        }

        setVisible(element_ != null);
    }
    
    private void TextFieldChanged() {
        if (element_ == null) return;
        
        element_.setLabel(NameTextField.getText());
        element_.setSrcMultiplicity(SourceMultTextField.getText());
        element_.setDestMultiplicity(DestMultTextField.getText());
        
        if (diagram_ != null) diagram_.notifyElementModified();
    }
    
    private class RelationDocumentListener implements DocumentListener {
        public void insertUpdate(DocumentEvent e) {
            TextFieldChanged();
        }

        public void removeUpdate(DocumentEvent e) {
            TextFieldChanged();
        }

        public void changedUpdate(DocumentEvent e) {
            TextFieldChanged();
        }
    
    }

    public void changePanelVisibility( Element selected) {
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DestMultLabel = new javax.swing.JLabel();
        DestMultTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        SourceMultLabel = new javax.swing.JLabel();
        SourceMultTextField = new javax.swing.JTextField();

        DestMultLabel.setText("Destination Multiplicity:");

        SourceMultLabel.setText("Source Multiplicity:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NameTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DestMultLabel)
                            .addComponent(SourceMultLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SourceMultTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(DestMultTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SourceMultLabel)
                    .addComponent(SourceMultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DestMultLabel)
                    .addComponent(DestMultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(723, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DestMultLabel;
    private javax.swing.JTextField DestMultTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel SourceMultLabel;
    private javax.swing.JTextField SourceMultTextField;
    // End of variables declaration//GEN-END:variables
}
