/*
 * Copyright (C) 2014 Patrick
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package classdiagrameditor;

import java.util.Set;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Patrick
 */
public class RelationshipPropertiesForm extends javax.swing.JPanel 
       implements SelectionObserver, DocumentListener {
        
    /**
     * Creates new form RelationshipPropertiesForm
     */
    private RelationshipElement element_;
    private DiagramManager diagram_;
    
    public RelationshipPropertiesForm() {
        initComponents();
    }
    
    @Override
    public void notifySelectionChanged(DiagramManager diagram, Set<Element> selection) {
        element_ = null;
        diagram_ = diagram;
        if (selection.size() == 1) {
            for (Element e : selection) {
                if (e instanceof RelationshipElement) {
                    element_ = (RelationshipElement)e;
                }
            changePanelVisibility(e);
            }
        }
        else
            changePanelVisibility(null);
        //Update the information in the relationship properties window
        NameTextField.setText(element_ == null ? "" : element_.getLabel());
        SourceMultTextField.setText(element_ == null ? "" : element_.getSrcMultiplicity());
        DestMultTextField.setText(element_ == null ? "" : element_.getDestMultiplicity());
    }
    
    private void nameTextChanged() {
        if (element_ == null && element_ == null) return;
        
        if (element_ != null) {
            element_.setLabel(NameTextField.getText());
        }
        
        if (diagram_ != null) diagram_.notifyElementModified();
    }
    
    public void insertUpdate(DocumentEvent e) {
        nameTextChanged();
    }

    public void removeUpdate(DocumentEvent e) {
        nameTextChanged();
    }

    public void changedUpdate(DocumentEvent e) {
        nameTextChanged();
    }

    public void changePanelVisibility( Element selected) {
        if (selected instanceof RelationshipElement) { 
            RelationshipPropertiesPanel.setVisible(true);
        }
        if (selected == null) {
            RelationshipPropertiesPanel.setVisible(false);
        }
        
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RelationshipPropertiesPanel = new javax.swing.JPanel();
        RelationshipPropertiesPanel.setVisible(false);
        DestMultLabel = new javax.swing.JLabel();
        DestMultTextField = new javax.swing.JTextField();
        NameTextField = new javax.swing.JTextField();
        SourceMultLabel = new javax.swing.JLabel();
        SourceMultTextField = new javax.swing.JTextField();

        DestMultLabel.setText("Destination Multiplicity:");

        SourceMultLabel.setText("Source Multiplicity:");

        javax.swing.GroupLayout RelationshipPropertiesPanelLayout = new javax.swing.GroupLayout(RelationshipPropertiesPanel);
        RelationshipPropertiesPanel.setLayout(RelationshipPropertiesPanelLayout);
        RelationshipPropertiesPanelLayout.setHorizontalGroup(
            RelationshipPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
            .addGroup(RelationshipPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelationshipPropertiesPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(RelationshipPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RelationshipPropertiesPanelLayout.createSequentialGroup()
                            .addGap(0, 17, Short.MAX_VALUE)
                            .addGroup(RelationshipPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DestMultLabel)
                                .addComponent(SourceMultLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(RelationshipPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SourceMultTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(DestMultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(NameTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap()))
        );
        RelationshipPropertiesPanelLayout.setVerticalGroup(
            RelationshipPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
            .addGroup(RelationshipPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RelationshipPropertiesPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addGroup(RelationshipPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SourceMultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SourceMultLabel))
                    .addGap(18, 18, 18)
                    .addGroup(RelationshipPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DestMultLabel)
                        .addComponent(DestMultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(240, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(RelationshipPropertiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RelationshipPropertiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 230, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DestMultLabel;
    private javax.swing.JTextField DestMultTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JPanel RelationshipPropertiesPanel;
    private javax.swing.JLabel SourceMultLabel;
    private javax.swing.JTextField SourceMultTextField;
    // End of variables declaration//GEN-END:variables
}
